-- AlterTable
ALTER TABLE "AppConfig" ADD COLUMN     "gemCostDoubleXp" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "gemCostHeartRefill" INTEGER NOT NULL DEFAULT 350,
ADD COLUMN     "gemCostStreakFreeze" INTEGER NOT NULL DEFAULT 200,
ADD COLUMN     "gemPack3000PriceEur" DOUBLE PRECISION NOT NULL DEFAULT 4,
ADD COLUMN     "gemPack500PriceEur" DOUBLE PRECISION NOT NULL DEFAULT 0.99,
ADD COLUMN     "gemPack7000PriceEur" DOUBLE PRECISION NOT NULL DEFAULT 7,
ADD COLUMN     "heartRefillPriceEur" DOUBLE PRECISION NOT NULL DEFAULT 1.99,
ADD COLUMN     "premiumFamilyMonthlyPriceEur" DOUBLE PRECISION NOT NULL DEFAULT 3.99,
ADD COLUMN     "premiumFamilyYearlyPriceEur" DOUBLE PRECISION NOT NULL DEFAULT 39.99,
ADD COLUMN     "premiumMonthlyPriceEur" DOUBLE PRECISION NOT NULL DEFAULT 1.52,
ADD COLUMN     "premiumYearlyPriceEur" DOUBLE PRECISION NOT NULL DEFAULT 15.24,
ADD COLUMN     "streakRepairPriceEur" DOUBLE PRECISION NOT NULL DEFAULT 0.87;
